#!/bin/bash

# Using jq, awk, and sed together
jq -r '. | "\(.name) \(.height) \(.weight) \(.types[0].type.name)"' data.json 2>/dev/null | \
awk '{
    print $1 " " $2 " " $3 " " $4
}' | \
sed 's/^./\U&\E/; s/ [^ ]*$/ \U&\E/' | \
awk '{
    # Now $1 is "Pikachu", $2 is height, $3 is weight, $4 is "Electric"
    formatted_height = $2 / 10
    formatted_weight = $3 / 10
    
    print $1 " is of type " $4 ", weighs " formatted_weight "kg, and is " formatted_height "m tall."
}'